### ISSUE TITLE
template not found

### ISSUE THREAD

**Issue by OskarStark** [indigophp/sonata-admin-print-bundle#5]
i got this error:
![bildschirmfoto 2016-01-14 um 17 07 45](https://cloud.githubusercontent.com/assets/995707/12329619/71629bb2-bae1-11e5-9f0c-ad6287ab6056.png)

any idea @sagikazarmark

**Comment by sagikazarmark** [comment]
See the usage section, point 3:

https://github.com/indigophp/sonata-admin-print-bundle#usage

Haven't found a better solution so far.

**Comment by OskarStark** [comment]
i did this:

``` php
            ->add('_action', 'actions', array(
                'actions' => array(
                    'show' => array(),
                    'edit' => array(),
                    'delete' => array(),
                    'print' => array(
                        'template' => 'SonataAdminPrintBundle::list__action_print.html.twig',
                    ),
                )
            ))
```

**Comment by OskarStark** [comment]
or what do you mean?

**Comment by sagikazarmark** [comment]
Yeah, I meant this one.

I don't know.

Here is an admin which works for me:

https://gist.github.com/sagikazarmark/3eba1c51e66d232b051b

If it doesn't help, I will try to find out what happens tommorrow.

**Comment by OskarStark** [comment]
hmm no, i got this error:

```
[Symfony\Component\Translation\Exception\InvalidResourceException]
  Invalid resource provided: "/Volumes/development/workspaces/tima-sonata/vendor/indigophp/sonata-admin-print-bundle/Resources/translations/SonataAdminPrin
  tBundle.de.xliff"; Errors: [ERROR 1871] Element '{urn:jms:translation}reference-file': This element is not expected. Expected is ( {urn:oasis:names:tc:xl
  iff:document:1.2}source ). (in /Volumes/development/workspaces/tima-sonata/ - line 14, column 0)
```

**Comment by sagikazarmark** [comment]
Oh shit, that's JMS translation bundle. You have to install that for now. But I already planned to kill that stuff.

**Comment by OskarStark** [comment]
check :)

**Comment by OskarStark** [comment]
this works:

``` php
        /* @var Response $response */
        $response = $this->render('SonataAdminPrintBundle::list__action_print.html.twig', [
            'action'   => 'print',
            'object'   => $object,
            'elements' => $this->admin->getShow(),
        ]);
```

could you please check that tomorrow, would be great :smile:

**Comment by sagikazarmark** [comment]
Will do.

**Comment by OskarStark** [comment]
looks like its working, but this is the result oO

<img width="1635" alt="bildschirmfoto 2016-01-14 um 20 37 24" src="https://cloud.githubusercontent.com/assets/995707/12335319/d9c902a0-bafe-11e5-9612-a8b8c18a24b4.png">

**Comment by sagikazarmark** [comment]
I think it uses the show field data fro your admin, which is not mandatory.

**Comment by OskarStark** [comment]
i have show fields, but it looks like it uses the template which is used in the List for the Action!

"Drucken" comes from the translation file from the button `action_print`

**Comment by sagikazarmark** [comment]
Hm, looks like the template must also be configured. Here is my admin service definition:

``` yaml


services:
    szerviz.admin.issue:
        class: SzervizBundle\Admin\IssueAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Szerviz", label: "Issue" }
        arguments:
            - ~
            - SzervizBundle\Entity\Issue
            - SzervizBundle:Issue
        calls:
            - [ setTranslationDomain, [SzervizBundle]]
            - [ setTemplate, [print, SonataAdminPrintBundle::print.html.twig]]
```
